name: registro_diario_mobil_1_0_1
description: "A new Flutter project."
publish_to: "none"
version: 1.0.0+1
environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  animated_splash_screen: ^1.3.0
  mysql1: ^0.20.0
  lottie: ^3.0.0
  provider: ^6.1.1
  shared_preferences: ^2.2.2
  connectivity_plus: ^5.0.2
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  intl: ^0.19.0
  radio_group_v2: ^3.1.0
  animated_custom_dropdown: ^3.0.0
  http: ^1.2.1
  searchable_paginated_dropdown: ^1.2.0
  status_alert: ^1.0.1


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_launcher_icons: "^0.13.1"

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/icon.png"
  min_sdk_android: 21 

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/lottie/
    - assets/icon/
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins-Light.ttf
        - asset: assets/fonts/Poppins-Medium.ttf
        - asset: assets/fonts/Poppins-Thin.ttf
